### ISSUE TITLE
NoMethodError · undefined method `call' for nil:NilClass

### ISSUE THREAD

**Issue by tibbon** [bugsnag/bugsnag-ruby#478]
After updating the bugsnag gem from 6.7.3 to 6.8.0 the following error started popping up in Bugsnag as soon as our Rails server started, and then periodically afterward. As you can see, there isn't terribly much information to go on. The error however did come in pairs, and always appeared twice in the Bugsnag UI. Nothing of note appeared in our logging service. 

I don't believe we have anything special happening in our bugsnag config, but if there are specific questions I can answer them. 

```
NoMethodError · undefined method `call' for nil:NilClass 
Did you mean? caller 
unknown file
unknown method
```

I stepped through the commits between 6.7.3 and 6.8.0 and narrowed it down between two listed below. Unfortunately, I don't see anything obvious that would trigger this, but the `os` gem is a new addition. 

WORKS: https://github.com/bugsnag/bugsnag-ruby/commit/327dd014cba2d35c2c0e6ea5de78160cc0488b7c
ERROR: https://github.com/bugsnag/bugsnag-ruby/commit/88f04913359578ce848a513b14644083d1fee7c3

**Comment by kattrali** [comment]
Thanks for the report, @tibbon, we are looking into it but haven't turned anything up yet. Can you share how you are configuring Bugsnag, such as the contents of your `config/initializers/bugsnag.rb` (minus the API key)? You can also send it support@bugsnag.com as well if there are sensitive contents or additional setup information that you wouldn't want to discuss on a public forum.

The commits in question only affect integration test gemsets, so there might be something else going on here.

**Comment by etlund** [comment]
I just upgraded Bugsnag to 6.8.0 in my Rails app and have started seeing these "undefined method 'call' for nil:NilClass" errors too. Each one corresponds to a WARN in my production.log:
`[Bugsnag]: Waiting for 1 outstanding request(s)`

My initializer is pretty minimal:
````
Bugsnag.configure do |config|
  config.api_key = 
  config.release_stage = Rails.env
  config.notify_release_stages = %w(production staging)
end
````

**Comment by etlund** [comment]
Hi!  I'm running Rails 5.1.6.  I think I upgraded from 5.25.2.

Thanks for checking it out.

**Comment by Cawllec** [comment]
I'm attempting to reproduce and track down the source of this issue.  It would be useful if you could let me know (securely at [support@bugsnag.com](support@bugsnag.com) if necessary):
- Gems used outside of the standard Rails 5 gemset
- Any configuration options being used (without specifics)
- The environment the app is running in (i.e. the operating system/cloud platform)

**Comment by Cawllec** [comment]
I'm still having trouble reproducing this issue.  It would be useful if anyone who has encountered this issue could present a reproduction case as a git repo if possible, and allow us to get this tracked down and fixed.

**Comment by lapluviosilla** [comment]
I believe we're having the same issue.
Rails 5.2.2
Bugsnag 6.11.1

Here's the stack trace:
```
NoMethodError
gems/bugsnag-6.11.1/lib/bugsnag/report.rb:192
undefined method `call' for nil:NilClass
Feb 21st, 2019, 21:50:39 UTC

STACKTRACE

gems/bugsnag-6.11.1/lib/bugsnag/report.rb:192:in `new': undefined method `call' for nil:NilClass (NoMethodError)
    from gems/bugsnag-6.11.1/lib/bugsnag/report.rb:192:in `block in generate_exception_list'
    from gems/bugsnag-6.11.1/lib/bugsnag/report.rb:188:in `map'
    from gems/bugsnag-6.11.1/lib/bugsnag/report.rb:188:in `generate_exception_list'
    from gems/bugsnag-6.11.1/lib/bugsnag/report.rb:50:in `initialize'
    from gems/bugsnag-6.11.1/lib/bugsnag.rb:70:in `new'
    from gems/bugsnag-6.11.1/lib/bugsnag.rb:70:in `notify'
    from gems/bugsnag-6.11.1/lib/bugsnag.rb:131:in `block in register_at_exit'
```

**Comment by snmaynard** [comment]
@lapluviosilla what webserver are you using? Is it happening at any particular time? I assume you are only seeing this when rails is running in webserver mode, and not in sidekiq/delayedjob etc etc.

**Comment by lapluviosilla** [comment]
We have 47 events in the last 3 days. Not sure what is triggering it.

We're running a rails app on Passenger Standalone, Ruby 2.5.3, on AWS Linux 2.9.0. Only web server mode, no background job.

**Comment by snmaynard** [comment]
Are you adding any before_notify callbacks anywhere yourself?

**Comment by lapluviosilla** [comment]
Yeah, but we've never had issues with this before:

```
module BugsnagReport
  extend ActiveSupport::Concern

  included do
    before_bugsnag_notify :add_user_info_to_bugsnag, if: :logged_in?
  end

  private
  # Adds user info for better debugging
  def add_user_info_to_bugsnag
    report.user = {
      id: current_user.id,
      username: current_user.username
    }
  end
end
```

**Comment by tobyhs** [comment]
I think this is due to https://github.com/phusion/passenger/issues/1730 as I was able to reproduce the issue with passenger 5.0.23, but couldn't reproduce it with the latest version (6.0.2).

**Comment by tobyhs** [comment]
For those affected by this error and are not in a position to upgrade Phusion Passenger, can you try the following monkey patch? (for a Rails app, create something in config/initializers/ such as config/initializers/passenger_signal_fix.rb)

```ruby
if defined?(PhusionPassenger::VERSION_STRING)
  if Gem::Version.new(PhusionPassenger::VERSION_STRING) < Gem::Version.new('5.0.24')
    # See https://github.com/phusion/passenger/issues/1730
    require 'phusion_passenger'
    PhusionPassenger.require_passenger_lib('ruby_core_enhancements')

    ORIGINAL_TRAPPABLE_SIGNALS = Signal.list_trappable

    module Signal
      def self.list_trappable
        ORIGINAL_TRAPPABLE_SIGNALS.reject { |k, _| k == 'EXIT' }
      end
    end
  else
    puts 'PhusionPassenger Signal.list_trappable monkey patch no longer needed'
  end
end
```
