### ISSUE TITLE
Resque.workers.new is complaining because called without queues

### ISSUE THREAD

**Issue by virgoproz** [bugsnag/bugsnag-ruby#354]
This commit breaks if I update 5.2.0 -> 5.3.0.

https://github.com/bugsnag/bugsnag-ruby/commit/091704afc425e50b400538a339e7222343d34f9e

I reverted this and I am good for now. Should be an easy fix :)

**Comment by snmaynard** [comment]
Which version of resque are you using?

**Comment by virgoproz** [comment]
* resque (1.27.2)
  * resque-cleaner (0.3.2)
  * resque-scheduler (4.3.0)

**Comment by virgoproz** [comment]
```
/Users/virgilio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/runtime.rb:94:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'bugsnag'.
Gem Load Error is: Please give each worker at least one queue.
Backtrace for gem load error is:
/Users/virgilio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/resque-1.27.2/lib/resque/worker.rb:188:in `validate_queues'
/Users/virgilio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/resque-1.27.2/lib/resque/worker.rb:179:in `queues='
/Users/virgilio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/resque-1.27.2/lib/resque/worker.rb:152:in `initialize'
/Users/virgilio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bugsnag-5.3.0/lib/bugsnag/resque.rb:40:in `new'
/Users/virgilio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bugsnag-5.3.0/lib/bugsnag/resque.rb:40:in `<top (required)>'
/Users/virgilio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bugsnag-5.3.0/lib/bugsnag.rb:127:in `require'
/Users/virgilio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bugsnag-5.3.0/lib/bugsnag.rb:127:in `block in <top (required)>'
/Users/virgilio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bugsnag-5.3.0/lib/bugsnag.rb:125:in `each'
/Users/virgilio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bugsnag-5.3.0/lib/bugsnag.rb:125:in `<top (required)>'
/Users/virgilio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/runtime.rb:91:in `require'
/Users/virgilio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
/Users/virgilio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/runtime.rb:86:in `each'
/Users/virgilio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/runtime.rb:86:in `block in require'
/Users/virgilio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/runtime.rb:75:in `each'
/Users/virgilio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.3/lib/bundler/runtime.rb:75:in `require'
/Users/virgilio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.3/lib/bundler.rb:107:in `require'
```

**Comment by sachin2919** [comment]
I am facing this issue when I updated bugsnag from 4.2 to 6.11.1

`rake aborted!
NoMethodError: undefined method `fork_per_job?' for #<Worker 0cf99830acee:449:bugsnag_fork_check>`

**Comment by mattdyoung** [comment]
Hi @sachin2919 

That's a different issue from the one previously raised here. Could you email support@bugsnag.com with the full details so we can investigate further?

We'd need details of the versions you're using (of resque in particular) and an example of how to reproduce.

Thanks!
