### ISSUE TITLE
NoMethodError after updating to 6.11.1

### ISSUE THREAD

**Issue by Jonathan-Arias** [bugsnag/bugsnag-ruby#555]
### Description
I’m trying to update the bugsnag gem from 6.10.0 to 6.11.1 for a rails application and the following error started to pop up when running the test suite. I'm able to run 6.10.0 without any issues.

```
undefined method `each_with_object' for nil:NilClass (NoMethodError)
/gems/bugsnag-6.11.1/lib/bugsnag/integrations/railtie.rb:82:in `block in event_subscription'
```

Might be related to using `mysql2` as [discussed here](https://github.com/bugsnag/bugsnag-ruby/pull/521#discussion_r245392743).

Configuration for bugsnag is pretty minimal.

```
Bugsnag.configure do |config|
  config.api_key =
  config.meta_data_filters +=
  config.release_stage ||= ENV['RAILS_ENV'] || 'development'
  config.ignore_classes += [SignalException, SystemExit]
end
```

### Environment
* Rails 3.2.22
* Bugsnag 6.11.1
* mysql2 0.3.21

**Comment by mattdyoung** [comment]
Hi

Yes, it looks like it may be related to using `mysql2`. We'll try to see if we can resolve this in bugsnag-ruby, and let you know when we have an update.

Thanks!

**Comment by mattdyoung** [comment]
Fixed in [v6.12.1](https://github.com/bugsnag/bugsnag-ruby/releases/tag/v6.12.1)

**Comment by xxx44yyy** [comment]
again

**Comment by xander-jones** [comment]
Hi @xxx44yyy, can you please let us know more detail about the error that you're seeing? Which version of Rails are you using? Is this related to `mysql2` too? If so, which version are you using.
